services:
  - type: web
    name: attendit
    runtime: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd server && npm install && node src/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
